force-app/main/default/objects/AdhocSchedule__c/AdhocSchedule__c.object-meta.xml
<CustomObject>
    <description>Records used by the Adhoc Scheduler utility to define ad-hoc jobs</description>
    <label>AdhocSchedule</label>
    <nameField>
        <label>AdhocSchedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdhocSchedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdhocSchedule__c/fields/Apex__c.field-meta.xml
<CustomField>
    <fullName>Apex__c</fullName>
    <description>The apex code which will be executed when the job is run</description>
    <inlineHelpText>The apex code which will be executed when the job is run</inlineHelpText>
    <label>Apex</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AdhocScheduler.cls
/**
 * @author KKnapp
 * @date 4/28/2023
 * @description 
 */
public without sharing class AdhocScheduler implements Schedulable {

   String sToExecute;

   @InvocableMethod
   public static void executeAdhoc(List<Id> adhocSchedulerIds){
      for (Id id : adhocSchedulerIds) {
         (new AdhocScheduler(id).runNow());
      }
   }

   public AdhocScheduler(String toExecute) {
      sToExecute = toExecute;
   }

   public AdhocScheduler(Id adhocId) {
      List<AdhocSchedule__c> records = AdhocSchedulerService.getRecordsById(new Set<Id>{adhocId});
      if (!records.isEmpty() && String.isNotBlank(records[0].Apex__c))
         sToExecute = records[0].Apex__c;
   }

   public void runNow() {
      AdhocToolingApiService.sendAnonApexAsync(sToExecute);
   }

   public void execute(SchedulableContext SC) {
      runNow();
   }

}