force-app/main/default/objects/AdhocSchedule__c/AdhocSchedule__c.object-meta.xml
<CustomObject>
    <description>Records used by the Adhoc Scheduler utility to define ad-hoc jobs</description>
    <label>AdhocSchedule</label>
    <nameField>
        <label>AdhocSchedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdhocSchedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdhocSchedule__c/fields/Apex__c.field-meta.xml
<CustomField>
    <fullName>Apex__c</fullName>
    <description>The apex code which will be executed when the job is run</description>
    <inlineHelpText>The apex code which will be executed when the job is run</inlineHelpText>
    <label>Apex</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AdhocSchedule__c/fields/CronString__c.field-meta.xml
<CustomField>
    <fullName>CronString__c</fullName>
    <description>Cron string to be used when scheduling the job.</description>
    <inlineHelpText>See syntax help at https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm</inlineHelpText>
    <label>Cron String</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdhocSchedule__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this adhoc scheduled job enabled?</description>
    <inlineHelpText>Check to enable this adhoc scheduled job. Uncheck to disable.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tests/AdhocScheduleTest.cls
/**
 * @author KKnapp
 * @date 5/7/2023
 * @description Covers the trigger and the trigger handler through basic dml
 */
@IsTest
public class AdhocScheduleTest {

   @IsTest
   public static void insert_update_covers() {
      AdhocToolingAPICalloutMock mockAuthResponse = new AdhocToolingAPICalloutMock(
         200,
         'OK',
         'OK',
         new Map<String, String>()
      );
      Test.setMock(HttpCalloutMock.class, mockAuthResponse);

      Test.startTest();
      AdhocSchedule__c adhoc = new AdhocSchedule__c(Name = 'test');
      adhoc.CronString__c = '00 35 8 * * ? *';
      insert adhoc;

      // we get a lot of coverage by doing an update
      adhoc.Name = 'updatedTest';
      adhoc.CronString__c = '00 36 8 * * ? *';
      adhoc.Apex__c = 'System.debug(\'Hello World!\');';
      adhoc.Enabled__c = true;
      update adhoc;
      delete adhoc;
      undelete adhoc;
      Test.stopTest();
   }
}